name: matrix action
on: push
jobs:
  build:
    strategy:
      matrix:
        node-version: [12, 14, 16],
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Install checkout
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install node stuff
        run: npm ci
      - name: Build project
        run: npm run build